<?php
/**
 * @Author: masoner
 * @Date 2022/5/30 12:20
 * @CourseTitle xxxx
 */

namespace common\models;

use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;


/**
 * @property integer id
 * @property string name
 * @property string code
 * @property string t_status
 */
class Supplier extends ActiveRecord
{

    public static function tableName(): string
    {
        return '{{%supplier}}'; // TODO: Change the autogenerated stub
    }

    public function behaviors(): array
    {
        return [
            TimestampBehavior::className()
        ];
    }

    public function rules(): array
    {
        return [
            [['id'], 'string'],
            [['name'], 'string'],
            [['code'], 'string'],
            [['t_status'], 'in', 'range'=>['ok', 'hold']],
        ]; // TODO: Change the autogenerated stub
    }


    /**
     * @param $params
     * @return ActiveDataProvider
     */
    public function search($params): ActiveDataProvider
    {
        $query = self::find();
        $provider = new ActiveDataProvider([
            'query'=>$query,
            'pagination'=>[
                'pageSize'=>10,
                // 'pageParam'=>'p',
                // 'pageSizeParam'=>'pageSize',
            ],
            'sort'=>[
                'defaultOrder'=>[
                    'id' => SORT_DESC
                ]
            ]
        ]);


        if (!($this->load($params) && $this->validate())){
            return $provider;
        }

        $query->andFilterCompare('id', $this->id)
                ->andFilterWhere(['like', 'name', $this->name])
                ->andFilterWhere(['like', 'code', $this->code])
                ->andFilterWhere(['t_status'=>$this->t_status]);

        return $provider;

    }

}